
name: ci
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout
      - name: ls
        run: |
            ls -la
            pwd
       